name	'jlondon-couchbase'
version	'0.0.9'
source  'UNKNOWN'
author  'Justice London'
license 'Apache License, Version 2.0'
summary 'Couchbase puppet module with scaling ability'
description 'This module allows you to configure and install a puppet based Couchbase cluster. Additionally you will be able to configure buckets (memcached or couchbase). Module requires concat and puppetdb.'
project_page 'http://github.com/justicel/puppet-couchbase'
dependency 'puppetlabs/concat', '>= 1.0.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'